'''Project Euler Problem 29
Find how many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100.'''

powerList = [a**b for a in range(2, 101) for b in range(2, 101)]
powerSet = set(powerList) # make the list a set to get the distinct values
powerList = list(powerSet) # change the set to a list
print len(powerList)